const CONFIG_LOADING = 'CONFIG_LOADING';
const CONFIG_SUCCESS = 'CONFIG_SUCCESS';
const CONFIG_FAILURE = 'CONFIG_FAILURE';

export const configActions = {
  CONFIG_LOADING,
  CONFIG_SUCCESS,
  CONFIG_FAILURE,
};